name: Node js app deploy to EKS
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: 
      - self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup EKS Kubectl
      uses: zachguo/setup-eks-kubectl@v1
      with:
       cluster: test-pipeline
       region: us-east-1
       namespace: default

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
             
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v2.0.4
      with:
       access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       region: us-east-1
    - name: Push to ECR
      run: |
        docker build -t test-pipeline .
        docker tag test-pipeline:latest 224841346245.dkr.ecr.us-east-1.amazonaws.com/test-pipeline:latest
        docker push 224841346245.dkr.ecr.us-east-1.amazonaws.com/test-pipeline:latest 


    - name: Update kube config
      run: aws eks update-kubeconfig --name test-pipeline
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
