name: Node js app deploy to EKS
on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: 
      - self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install   

    - name: Setup EKS Kubectl
      uses: zachguo/setup-eks-kubectl@v1
      with:
       cluster: test-pipeline
       region: us-east-1
       namespace: default
             
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v2.0.4
      with:
       access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       region: us-east-1
    - name: Push to ECR
      run: |
        docker build -t test-pipeline:${{ github.run_number }} .
        docker tag test-pipeline:${{ github.run_number }} 224841346245.dkr.ecr.us-east-1.amazonaws.com/test-pipeline:${{ github.run_number }}
        docker push 224841346245.dkr.ecr.us-east-1.amazonaws.com/test-pipeline:${{ github.run_number }} 

    - name: Update kube config
      run: aws eks update-kubeconfig --name test-pipeline
      
    - name: Update deployment file
      env:
        ECR_REPO_URL: 224841346245.dkr.ecr.us-east-1.amazonaws.com/test-pipeline
        RUNNER_NUMBER: ${{ github.run_number }}
      run: |
        sed -i "s|image:.*|image: $ECR_REPO_URL:$RUNNER_NUMBER|g"  deployment.yaml
        cat deployment.yaml 
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,action,eventName,workflow,time,status
          mentions: '@channel'
          pretext: 'New code pushed to *main* branch'
          color: ${{ job.status == 'success' }} # green for success, red for failure   
